---
- hosts: nodes
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Creating a Directory
    file:
      path: /root/gitrepo
      state: directory
      
  - name: Installing git on Debian flavour
    yum:
      name: git
      state: present
      update_cache: yes
    when:  ansible_facts['os_family'] == "Debian"
      
  - name: Cloaing playbook from repo
    ansible.builtin.git:
      repo: 
      dest: /root/gitrepo
      
  - name: installing tomcat CentOS
    package:
      name: tomcat
      state: present
    when:  ansible_facts['os_family'] == "RedHat"
  - name: installing tomcat Ubuntu
    package:
      name: tomcat9
      state: present
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting tomcat CentOS
    service:
      name: tomcat
      state: started
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: started
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting up tomcat CentOS 
    service:
      name: tomcat
      state: restarted
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: restarted
    when:  ansible_facts['os_family'] == "Debian"
  - name: copying addressbook file CentOS
    copy:
      src: /home/ubuntu/workspace/projects1/addressbook_main/target/addressbook.war
      dest: /usr/share/tomcat/webapps
    when:  ansible_facts['os_family'] == "RedHat"
  - name: copying addressbook file Ubuntu
    copy:
      src: /home/ubuntu/workspace/projects1/addressbook_main/target/addressbook.war
      dest: /var/lib/tomcat9/webapps
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting up tomcat CentOS 
    service:
      name: tomcat
      state: restarted
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: restarted
    when:  ansible_facts['os_family'] == "Debian"
